server:
  port: 8888
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/api/v1/user/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/api/v1/hotel/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/api/v1/rating/**  
          
    
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

  config:
    import: optional:configserver:http://localhost:9090
    
    
#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-40691717.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8bqbagjouuq30e5d7
    client-secret: 0E_G866I3PkAdh1AZHhcFG21q-LFSRHFnSl2Ymli
    scopes: openid, profile, email, offline_access
    
    